In [1]:
import numpy as np
import gym
import tensorflow as tf
from tensorflow.contrib.layers import flatten, conv2d, fully_connected
from collections import deque, Counter
import random
from datetime import datetime
import time
import pickle
import numpy as np
from functools import reduce
import cv2

In [12]:
color = np.array([210, 164, 74]).mean()

def preprocess_observation(obs):

    
    # Crop and resize the image
    img = obs[20:196:2, ::2]
    
    cv2.imwrite('lolz.jpg', img)
    
    # Convert the image to greyscale
    img = img.mean(axis=2)
    
    # Improve image contrast
    img[img==color] = 0
    
    # Next we normalize the image from -1 to +1
    img = img/255
    
    img = img.reshape(88,80,1)
    
    return img

In [18]:
env = gym.make("SpaceInvaders-v0")
n_outputs = env.action_space.n


6

In [19]:
obs = env.reset()
done = False

tf.reset_default_graph()
with tf.Session() as sess:
    new_saver = tf.train.import_meta_graph('./models/trained-model-800.meta')
    sess.run(tf.global_variables_initializer())
    new_saver.restore(sess, './models/trained-model-800')


    episodic_reward = 0
    mainQ_outputs = sess.graph.get_tensor_by_name('mainQ/fully_connected_1/BiasAdd:0')
    
    X = sess.graph.get_tensor_by_name('X:0')
    in_training_mode = sess.graph.get_tensor_by_name('in_training_mode:0')
    count = 0

    while not done:

        env.render()

        obs = preprocess_observation(obs)
        
        last_obs = obs

        actions = mainQ_outputs.eval(feed_dict={X:[obs], in_training_mode:False})
        print(actions);
        
        action = np.argmax(actions, axis=-1)
        
        next_obs, reward, done, _ = env.step(action)
        obs = next_obs
        episodic_reward += reward
        count += 1
        time.sleep(0.05)
    print(episodic_reward)
    env.close()

INFO:tensorflow:Restoring parameters from ./models/trained-model-800
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.704605

[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[2.994584  2.9376326 2.9833467 2.840264  2.9688153 3.089741 ]]
[[2.4069836 2.3731923 2.3910587 2.2541013 2.3547194 2.476234 ]]
[[2.6960123 2.6508288 2.682393  2.5424228 2.6567807 2.7780056]]
[[2.6939452 2.6488433 2.6803095 2.5403607 2.6546202 2.7758472]]
[[2.6644728 2.6205325 2.650602  2.5109606 2.623819  2.7450755]]
[[2.7841265 2.73547   2.7712102 2.6303213 2.748868  2.8700044]]
[[2.770203  2.7220955 2.7571757 2.616432  2.7343168 2.8554673]]
[[2.357258  2.3254268 2.3409367 2.2044973 2.3027518 2.4243162]]
[[2.4069836 2.3731923 2.3910587 2.2541013 2.3547194 2.476234 ]]
[[2.4069836 2.3731923 2.3910587 2.2541013 2.3547194 2.476234 ]]
[[2.503034  2.465457  2.4878755 2.3499167 2.4551008 2.5765193]]
[[4.5416603 4.5798936 4.6160917 5.0404406 4.2887554 4.7689214]]
[[4.5416603 4.5798936 

[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.7046053  0.6401486  0.52129775 0.5393416  0.6625971 ]]
[[0.66993004 0.70460

[[1.4345297 1.3893275 1.3483651 1.0619009 1.345643  1.3661208]]
[[0.82122743 0.8105705  0.743199   0.49641594 0.7031802  0.7455436 ]]
[[2.2701254 2.1035113 1.9954662 1.4726448 2.044222  1.9101202]]
[[ 0.08079869  0.02760923 -0.2113542  -0.6014077  -0.32390773 -0.38892   ]]
[[-0.57552546 -0.5721598  -0.87943536 -1.133949   -1.1148856  -1.1014419 ]]
[[-0.6894149 -0.6954455 -1.0107627 -1.3092656 -1.2298563 -1.245076 ]]
[[-0.4526947  -0.48091227 -0.7496913  -1.11781    -0.89440113 -0.94896203]]
[[1.8608222 1.7194798 1.6089718 1.1099653 1.6477127 1.52795  ]]
[[4.076126  3.7875626 3.8361218 3.0752208 4.1265774 3.85884  ]]
[[ 0.4904057   0.39786676  0.23826534 -0.27470583  0.25462943  0.11988217]]
[[1.0990466  1.0127276  0.8605486  0.45774028 0.821231   0.75744873]]
[[1.0990466  1.0127276  0.8605486  0.45774028 0.821231   0.75744873]]
[[1.0990466  1.0127276  0.8605486  0.45774028 0.821231   0.75744873]]
[[1.5268021  1.3850234  1.2115564  0.73960525 1.304415   1.1099973 ]]
[[1.5268021  1.38502

[[7.1950755 7.3680286 7.6660447 6.5176706 7.447846  7.4263988]]
[[5.9904437 6.1886272 6.406446  5.1343436 6.165396  6.070021 ]]
[[7.641791  7.757451  8.086015  6.8353887 7.962477  7.868689 ]]
[[7.4491887 7.5393143 7.8625646 6.463081  7.7980733 7.6166015]]
[[6.2145963 6.3912086 6.637344  5.374759  6.4427476 6.3411536]]
[[10.15642  10.031075 10.281925  9.093764 10.172517 10.047304]]
[[13.124379 12.886604 13.280676 12.088278 13.247126 13.154119]]
[[12.595784 12.423086 12.764113 11.678431 12.604502 12.589672]]
[[10.387237 10.317551 10.529023  9.49829  10.2438   10.249542]]
[[8.393134 8.376161 8.480904 7.443238 8.157018 8.126874]]
[[7.0457244 7.025299  7.092953  5.905019  6.853522  6.7073417]]
[[7.3690705 7.3493843 7.422872  6.3641186 7.1641345 7.074656 ]]
[[8.659343 8.589872 8.699646 7.745767 8.45346  8.408992]]
[[11.032676 10.871827 11.078124 10.257362 10.905807 10.910178]]
[[10.409808  10.271857  10.525166   9.294755  10.4202585 10.277826 ]]
[[10.30503  10.200958 10.434929  9.581126 10.2

[[3.143578  3.4759295 3.6420398 3.203015  3.2940395 3.5395446]]
[[2.9439235 3.2694533 3.4130921 2.9703176 3.069267  3.2982116]]
[[2.8247132 3.1452801 3.2867541 2.8547904 2.9622724 3.182754 ]]
[[2.523417  2.8598206 2.9846787 2.5178382 2.6442611 2.8524299]]
[[2.3087897 2.6634781 2.7510638 2.2921326 2.3605373 2.5771403]]
[[2.3458104 2.7019675 2.785953  2.282173  2.3886364 2.5907474]]
[[1.9638486 2.329118  2.4109569 1.8105562 2.0296266 2.1899438]]
[[2.026054  2.3702614 2.484324  1.7419388 2.1694458 2.2629561]]
[[4.36807   4.7961864 4.9643273 4.678243  4.3942246 4.805242 ]]
[[4.8099723 5.215888  5.4053435 5.1169877 4.8574204 5.266231 ]]
[[4.4340796 4.863289  5.0266385 4.754211  4.438892  4.862085 ]]
[[5.20834   5.562891  5.780503  5.3677106 5.3109326 5.649075 ]]
[[5.926355  6.227174  6.4662614 6.0263476 6.0453143 6.3570743]]
[[6.0534024 6.3933926 6.633014  6.3750834 6.1304193 6.5513577]]
[[6.005381  6.3745346 6.6141543 6.4510026 6.0627856 6.5446754]]
[[4.239779  4.6824512 4.819573  4.623327

[[1.8186264 1.8357937 1.7619429 0.9066747 1.6748016 1.5094662]]
[[2.5045938 2.4840262 2.4494343 1.6215327 2.406778  2.2471867]]
[[4.3404436 4.28047   4.310706  3.6647875 4.2309837 4.1886406]]
[[4.4692926 4.414361  4.440884  3.7701287 4.3503156 4.300389 ]]
[[6.8746433 6.898407  7.0025496 6.889636  6.637479  6.9734435]]
[[7.305285  7.321948  7.440184  7.3743153 7.063106  7.4289865]]
[[7.4878097 7.521864  7.6430244 7.647815  7.2270117 7.63952  ]]
[[5.841071  5.9803586 6.0440316 6.0483007 5.531159  5.970406 ]]
[[6.10222   6.2209587 6.2988076 6.2718215 5.8210397 6.235945 ]]
[[6.3362913 6.3933916 6.504617  6.2645507 6.1571207 6.4431286]]
[[7.736359  7.7827964 7.9331245 7.955851  7.5085764 7.9485536]]
[[8.255868 8.221013 8.406201 8.175523 8.124694 8.413761]]
[[7.756099  7.754994  7.9091005 7.7450356 7.57526   7.900745 ]]
[[6.4058747 6.494238  6.5815086 6.5530233 6.1321144 6.5360475]]
[[7.8051434 7.870055  7.9841623 8.184698  7.480339  8.003806 ]]
[[7.0297284 7.084212  7.1388936 7.2355595 6.66

[[9.921181 9.58063  9.809983 8.733168 9.999549 9.742536]]
[[9.531199 9.209651 9.40817  8.388841 9.559241 9.327634]]
[[9.921181 9.58063  9.809983 8.733168 9.999549 9.742536]]
[[9.921181 9.58063  9.809983 8.733168 9.999549 9.742536]]
[[9.531199 9.209651 9.40817  8.388841 9.559241 9.327634]]
[[9.921181 9.58063  9.809983 8.733168 9.999549 9.742536]]
[[9.921181 9.58063  9.809983 8.733168 9.999549 9.742536]]
[[9.531199 9.209651 9.40817  8.388841 9.559241 9.327634]]
[[9.921181 9.58063  9.809983 8.733168 9.999549 9.742536]]
[[9.531199 9.209651 9.40817  8.388841 9.559241 9.327634]]
[[9.531199 9.209651 9.40817  8.388841 9.559241 9.327634]]
[[9.921181 9.58063  9.809983 8.733168 9.999549 9.742536]]
[[9.921181 9.58063  9.809983 8.733168 9.999549 9.742536]]
[[9.531199 9.209651 9.40817  8.388841 9.559241 9.327634]]
[[9.921181 9.58063  9.809983 8.733168 9.999549 9.742536]]
[[9.921181 9.58063  9.809983 8.733168 9.999549 9.742536]]
[[9.531199 9.209651 9.40817  8.388841 9.559241 9.327634]]
[[9.921181 9.5

[[5.932298  5.7475634 5.5967755 5.114309  5.4514346 5.372082 ]]
[[5.932298  5.7475634 5.5967755 5.114309  5.4514346 5.372082 ]]
[[5.932298  5.7475634 5.5967755 5.114309  5.4514346 5.372082 ]]
[[4.020964  3.7870662 3.60392   2.6717837 3.658591  3.3035312]]
[[4.020964  3.7870662 3.60392   2.6717837 3.658591  3.3035312]]
[[4.020964  3.7870662 3.60392   2.6717837 3.658591  3.3035312]]
[[4.020964  3.7870662 3.60392   2.6717837 3.658591  3.3035312]]
[[4.020964  3.7870662 3.60392   2.6717837 3.658591  3.3035312]]
[[4.020964  3.7870662 3.60392   2.6717837 3.658591  3.3035312]]
[[4.020964  3.7870662 3.60392   2.6717837 3.658591  3.3035312]]
[[4.020964  3.7870662 3.60392   2.6717837 3.658591  3.3035312]]
[[3.3297791 3.090546  2.9212317 2.023875  3.0681427 2.6835904]]
[[3.3297791 3.090546  2.9212317 2.023875  3.0681427 2.6835904]]
[[3.3297791 3.090546  2.9212317 2.023875  3.0681427 2.6835904]]
[[3.3297791 3.090546  2.9212317 2.023875  3.0681427 2.6835904]]
[[3.3297791 3.090546  2.9212317 2.023875

[[-2.3218055 -1.8668735 -2.1018357 -3.1980083 -2.7103589 -2.7587562]]
[[-1.5644841 -1.1544607 -1.2669206 -2.2571204 -1.904855  -1.8167977]]
[[-3.1359582 -2.779518  -3.0152783 -4.28964   -3.5695622 -3.6936927]]
[[-2.613871  -2.1811407 -2.4591765 -3.579889  -3.062031  -3.14564  ]]
[[-2.3122983 -1.8028753 -2.0651402 -3.0296628 -2.728058  -2.7206645]]
[[-2.3218055 -1.8668735 -2.1018357 -3.1980083 -2.7103589 -2.7587562]]
[[-1.5644841 -1.1544607 -1.2669206 -2.2571204 -1.904855  -1.8167977]]
[[-1.5644841 -1.1544607 -1.2669206 -2.2571204 -1.904855  -1.8167977]]
[[-2.776157  -2.286517  -2.57581   -3.7112424 -3.1771166 -3.2807078]]
[[-1.5644841 -1.1544607 -1.2669206 -2.2571204 -1.904855  -1.8167977]]
[[-2.3218055 -1.8668735 -2.1018357 -3.1980083 -2.7103589 -2.7587562]]
[[-1.5644841 -1.1544607 -1.2669206 -2.2571204 -1.904855  -1.8167977]]
[[-2.3218055 -1.8668735 -2.1018357 -3.1980083 -2.7103589 -2.7587562]]
[[-2.3218055 -1.8668735 -2.1018357 -3.1980083 -2.7103589 -2.7587562]]
[[-1.5644841 -1.1544