In [26]:
import numpy as np
import gym
import tensorflow as tf
from tensorflow.contrib.layers import flatten, conv2d, fully_connected
from collections import deque, Counter
import random
from datetime import datetime
import time
import pickle
import numpy as np
from functools import reduce
import cv2

In [42]:
color = np.array([210, 164, 74]).mean()

def preprocess_observation(obs):
    # Crop and resize the image
    img = obs[20:196:2, ::2]

    
    # Convert the image to greyscale
    img = img.mean(axis=2)
    
    # Improve image contrast
    img[img==color] = 0
    
    # Next we normalize the image from -1 to +1
    img = img/255
    
    img = img.reshape(88,80,1)
    
    return img

In [43]:
env = gym.make("SpaceInvaders-v0")
n_outputs = env.action_space.n


In [48]:
obs = env.reset()
done = False

tf.reset_default_graph()
with tf.Session() as sess:
    new_saver = tf.train.import_meta_graph('./trained-model.meta')
    new_saver.restore(sess, './trained-model')

    episodic_reward = 0
    mainQ_outputs = sess.graph.get_tensor_by_name('mainQ/fully_connected_1/BiasAdd:0')
    
    X = sess.graph.get_tensor_by_name('X:0')
    in_training_mode = sess.graph.get_tensor_by_name('in_training_mode:0')
    count = 0

    while not done:

        env.render()

        obs = preprocess_observation(obs)
        
        last_obs = obs

        actions = mainQ_outputs.eval(feed_dict={X:[obs], in_training_mode:False})
        print(actions);
        
        action = np.argmax(actions, axis=-1)
        
        next_obs, reward, done, _ = env.step(action)
        obs = next_obs
        episodic_reward += reward
        count += 1
        time.sleep(0.05)
    print(episodic_reward)
    env.close()

INFO:tensorflow:Restoring parameters from ./trained-model
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.23

[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.109277

[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.109277

[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.109277

[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.109277

[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.109277

[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.109277

[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.1092775 3.2347832 3.2547555]]
[[3.1782143 3.0809526 3.2073238 3.109277